// -------------------------------------------------------------------------
//  TELA MODELO PARA VISÃO DO INVESTIDOR 
//
// -------------------------------------------------------------------------
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matheus.sibov.view.investidor;

import org.matheus.perfis.Usuario;
import org.matheus.sibov.service.UsuarioService;

import org.matheus.sibov.view.TelaDeLogin;

/**
 *
 * @author mathe
 */
public class VisaoInvestidor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoInvestidor.class.getName());
    private Usuario usuarioLogado;
    private UsuarioService usuarioService;

    /**
     * Creates new form VisaoInvestidor
     */
    public VisaoInvestidor() {
        initComponents();

        this.usuarioService = new UsuarioService();
        carregarDadosUsuario();
    }

    // Novo construtor que recebe o usuário logado
    public VisaoInvestidor(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        this.usuarioService = new UsuarioService();
        initComponents();
        carregarDadosUsuario();
    }

    // -------------------------------------------------------------------------
    //  METODO PARA CARREGAR OS DADOS DO USUARIO LOGADO
    // -------------------------------------------------------------------------
    private void carregarDadosUsuario() {

        if (usuarioLogado != null) {
            VerUsuarioLogado.setText(usuarioLogado.getNome());

            txtSaldo.setText(usuarioService.obterSaldoFormatado(usuarioLogado.getId()));

            txtNumeroConta.setText(String.valueOf(usuarioLogado.getId()));

        } else {
            VerUsuarioLogado.setText("Usuário não identificado");
            txtSaldo.setText("R$ 0,00");
        }
    }

    public void atualizarSaldo() {
        if (usuarioLogado != null) {
            txtSaldo.setText(usuarioService.obterSaldoFormatado(usuarioLogado.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        PainelVerdeSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelVerdeInferior = new javax.swing.JPanel();
        Logado = new javax.swing.JLabel();
        VerUsuarioLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCarteira = new javax.swing.JMenu();
        BtnComprarAtivo = new javax.swing.JMenuItem();
        BtnDepositarSacar = new javax.swing.JMenuItem();
        btnProventos = new javax.swing.JMenu();
        MenuItemProventosPagos = new javax.swing.JMenuItem();
        MenuItemProventosAgendados = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        MenuSuperiorExtratoDoUsuario = new javax.swing.JMenuItem();
        BtnCorretoras = new javax.swing.JMenu();
        MenuItemSimulador = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do Investidor - Sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PainelVerdeSuperior.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Investidor");

        javax.swing.GroupLayout PainelVerdeSuperiorLayout = new javax.swing.GroupLayout(PainelVerdeSuperior);
        PainelVerdeSuperior.setLayout(PainelVerdeSuperiorLayout);
        PainelVerdeSuperiorLayout.setHorizontalGroup(
            PainelVerdeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
        );
        PainelVerdeSuperiorLayout.setVerticalGroup(
            PainelVerdeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVerdeSuperiorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PainelVerdeInferior.setBackground(new java.awt.Color(0, 102, 102));

        Logado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Logado.setText("Usuário logado:");

        VerUsuarioLogado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VerUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        VerUsuarioLogado.setText("Matheus Ribeiro");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Saldo:");

        txtSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setText("R$ 0,00");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Conta:");

        txtNumeroConta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumeroConta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroConta.setText("01");

        javax.swing.GroupLayout PainelVerdeInferiorLayout = new javax.swing.GroupLayout(PainelVerdeInferior);
        PainelVerdeInferior.setLayout(PainelVerdeInferiorLayout);
        PainelVerdeInferiorLayout.setHorizontalGroup(
            PainelVerdeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVerdeInferiorLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VerUsuarioLogado)
                .addGap(127, 127, 127)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSaldo)
                .addGap(119, 119, 119)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(txtNumeroConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelVerdeInferiorLayout.setVerticalGroup(
            PainelVerdeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVerdeInferiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PainelVerdeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logado)
                    .addComponent(VerUsuarioLogado)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldo)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroConta))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnCarteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carteira.png"))); // NOI18N
        btnCarteira.setText("Carteira");
        btnCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteiraActionPerformed(evt);
            }
        });

        BtnComprarAtivo.setText("Compra - Venda de Ativo");
        BtnComprarAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarAtivoActionPerformed(evt);
            }
        });
        btnCarteira.add(BtnComprarAtivo);

        BtnDepositarSacar.setText("Depositar - Sacar");
        BtnDepositarSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDepositarSacarActionPerformed(evt);
            }
        });
        btnCarteira.add(BtnDepositarSacar);

        jMenuBar1.add(btnCarteira);

        btnProventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pagamentos.png"))); // NOI18N
        btnProventos.setText("Proventos");

        MenuItemProventosPagos.setText("Proventos Pagos");
        MenuItemProventosPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventosPagosActionPerformed(evt);
            }
        });
        btnProventos.add(MenuItemProventosPagos);

        MenuItemProventosAgendados.setText("Proventos Agendados");
        MenuItemProventosAgendados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventosAgendadosActionPerformed(evt);
            }
        });
        btnProventos.add(MenuItemProventosAgendados);

        jMenuBar1.add(btnProventos);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impressora.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        MenuSuperiorExtratoDoUsuario.setText("Extrato de caixa");
        MenuSuperiorExtratoDoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSuperiorExtratoDoUsuarioActionPerformed(evt);
            }
        });
        btnRelatorios.add(MenuSuperiorExtratoDoUsuario);

        jMenuBar1.add(btnRelatorios);

        BtnCorretoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/images/vendas.png"))); // NOI18N
        BtnCorretoras.setText("Corretagem");
        BtnCorretoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCorretorasActionPerformed(evt);
            }
        });

        MenuItemSimulador.setText("Simulador");
        MenuItemSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSimuladorActionPerformed(evt);
            }
        });
        BtnCorretoras.add(MenuItemSimulador);

        jMenuBar1.add(BtnCorretoras);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelVerdeSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelVerdeInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelVerdeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(PainelVerdeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // Para abrir a janela já maximizada, adicionado esse trecho de código:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);

        carregarDadosUsuario();
    }//GEN-LAST:event_formWindowActivated

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked

        // Fechar a Janela atual
        this.dispose();

        // Abre a tela de login novamente
        new TelaDeLogin().setVisible(true);

    }//GEN-LAST:event_btnSairMouseClicked


    private void BtnDepositarSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDepositarSacarActionPerformed

        // Chama a tela de depositos e saques
        new VisaoInvestidorDepositos(usuarioLogado).setVisible(true);
        this.dispose(); // Fecha a tela principal

    }//GEN-LAST:event_BtnDepositarSacarActionPerformed


    private void BtnComprarAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarAtivoActionPerformed

        // Vai para a tela de compra de Ativos :
        new VisaoInvestidorCompraAtivo(usuarioLogado).setVisible(true);
        this.dispose(); // Fecha a tela atual (opcional)

    }//GEN-LAST:event_BtnComprarAtivoActionPerformed

    private void MenuSuperiorExtratoDoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSuperiorExtratoDoUsuarioActionPerformed
        new VisaoInvestidorExtrato(usuarioLogado).setVisible(true); // Passando o Usuário Logado
    this.dispose(); // fecha a tela atual
    }//GEN-LAST:event_MenuSuperiorExtratoDoUsuarioActionPerformed

    private void MenuItemProventosAgendadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventosAgendadosActionPerformed
         new VisaoInvestidorProventosAgendados(usuarioLogado).setVisible(true); // Passando o Usuário Logado
    this.dispose(); // fecha a tela atual
    }//GEN-LAST:event_MenuItemProventosAgendadosActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarteiraActionPerformed

    private void MenuItemProventosPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventosPagosActionPerformed
         new VisaoInvestidorProventosPagos(usuarioLogado).setVisible(true); // Passando o Usuário Logado
    this.dispose(); // fecha a tela atual
    }//GEN-LAST:event_MenuItemProventosPagosActionPerformed

    private void BtnCorretorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCorretorasActionPerformed
         
    }//GEN-LAST:event_BtnCorretorasActionPerformed

    private void MenuItemSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSimuladorActionPerformed
        new VisaoInvestidorCorretagem(usuarioLogado).setVisible(true); // Passando o Usuário Logado
    this.dispose(); // fecha a tela atual
    }//GEN-LAST:event_MenuItemSimuladorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisaoInvestidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnComprarAtivo;
    private javax.swing.JMenu BtnCorretoras;
    private javax.swing.JMenuItem BtnDepositarSacar;
    private javax.swing.JLabel Logado;
    private javax.swing.JMenuItem MenuItemProventosAgendados;
    private javax.swing.JMenuItem MenuItemProventosPagos;
    private javax.swing.JMenuItem MenuItemSimulador;
    private javax.swing.JMenuItem MenuSuperiorExtratoDoUsuario;
    private javax.swing.JPanel PainelVerdeInferior;
    private javax.swing.JPanel PainelVerdeSuperior;
    private javax.swing.JLabel VerUsuarioLogado;
    private javax.swing.JMenu btnCarteira;
    private javax.swing.JMenu btnProventos;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel txtNumeroConta;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables
}
