/* ---------------------------------------------------------------------------- */
// Processamento do evento - Conceitos Básicos : 
//  - Quantidade total detida (somatório de carteira_ativos.quantidade_total) – impacto agregado
// - Valor total estimado (cálculo: valor_por_cota × quantidade_total) – visão financeira do evento
// - Data COM  – quem tem direito
// Data EX  – quem não tem mais direito
//
// O Botão processa a linha seelciona, mas a condição de processamento está pelo ID do Ticket, então processa para todos os usuários que tiver o ticket igual
//
/* ---------------------------------------------------------------------------- */
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matheus.sibov.view.admin;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.matheus.perfis.Usuario;
import org.matheus.sibov.dao.ProcessarEventoDAO;
import org.matheus.sibov.view.TelaDeLogin;

import org.matheus.sibov.view.admin.VisaoAdmCadastroUsers;

/**
 *
 * @author mathe
 */
public class VisaoAdministradorProcessarEvento extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoAdministradorProcessarEvento.class.getName());

    /**
     * Creates new form VisaoAdministrador
     */
    private Usuario usuarioLogado;

    public VisaoAdministradorProcessarEvento() {
        initComponents();
    }

    public VisaoAdministradorProcessarEvento(Usuario user) {
        this.usuarioLogado = user;
        initComponents();
        carregarDadosUsuario();
    }

    private void carregarDadosUsuario() {
        if (usuarioLogado != null) {
            txtUsuarioLogado.setText(usuarioLogado.getNome());
        }
    }
    
    
    
    
    /*  Chamar a DAO para preencher a tabela */
    private void carregarTabelaEventos() {
    DefaultTableModel modelo = (DefaultTableModel) TabelaProcessamentoDoEvento.getModel();
    modelo.setRowCount(0);

    ProcessarEventoDAO dao = new ProcessarEventoDAO();
    List<Object[]> dados = dao.listarEventosParaProcessamento();

    for (Object[] linha : dados) {
        modelo.addRow(linha);
    }
}

    
    
     /*  Chamar a DAO para Mudar o status de agendado para pago: */
   
    private void processarEventoSelecionado() {
    int linhaSelecionada = TabelaProcessamentoDoEvento.getSelectedRow();
    if (linhaSelecionada != -1) {
        int idEvento = (int) TabelaProcessamentoDoEvento.getValueAt(linhaSelecionada, 0);

        ProcessarEventoDAO dao = new ProcessarEventoDAO();
        dao.processarEventoComCredito(idEvento); // método completo que atualiza tudo

        JOptionPane.showMessageDialog(this,
            "Evento processado com sucesso! Valor creditado na carteira e registrado no histórico.",
            "Processamento concluído",
            JOptionPane.INFORMATION_MESSAGE);

        carregarTabelaEventos();
    } else {
        JOptionPane.showMessageDialog(this,
            "Selecione um evento para processar.",
            "Aviso",
            JOptionPane.WARNING_MESSAGE);
    }
}


    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logado = new javax.swing.JLabel();
        txtUsuarioLogado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProcessamentoDoEvento = new javax.swing.JTable();
        BotaoProcessamentoDoEvento = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnCadastro = new javax.swing.JMenu();
        btnCadastrarAtivos = new javax.swing.JMenuItem();
        btnCadastrarUsuarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuItemProvento = new javax.swing.JMenuItem();
        BtnControle = new javax.swing.JMenu();
        MenuItemEstorno = new javax.swing.JMenuItem();
        MenuItemProcessarEvento = new javax.swing.JMenuItem();
        MenuItemLogs = new javax.swing.JMenu();
        LogOperacoesCarteira = new javax.swing.JMenuItem();
        MenuItemEventosProcessados = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel administrativo do sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EVENTOS AGENDADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        Logado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Logado.setText("Usuário logado:");

        txtUsuarioLogado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuarioLogado.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuarioLogado.setText("Matheus Ribeiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioLogado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logado)
                    .addComponent(txtUsuarioLogado))
                .addGap(34, 34, 34))
        );

        TabelaProcessamentoDoEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID da Operação", "Ticket", "Tipo de Ativo", "Segmento", "Tipo de Provento", "Valor por Cota", "Data COM", "Data EX", "Data de Pagamento", "Status", "Qtde Total Detida", "Valor Total Estimado"
            }
        ));
        jScrollPane1.setViewportView(TabelaProcessamentoDoEvento);

        BotaoProcessamentoDoEvento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotaoProcessamentoDoEvento.setText("Processar Evento");
        BotaoProcessamentoDoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProcessamentoDoEventoActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        BtnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/novo.png"))); // NOI18N
        BtnCadastro.setText("Cadastros");

        btnCadastrarAtivos.setText("Ativos");
        btnCadastrarAtivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarAtivosMouseClicked(evt);
            }
        });
        btnCadastrarAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtivosActionPerformed(evt);
            }
        });
        BtnCadastro.add(btnCadastrarAtivos);

        btnCadastrarUsuarios.setText("Usuários");
        btnCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuariosActionPerformed(evt);
            }
        });
        BtnCadastro.add(btnCadastrarUsuarios);

        jMenuItem1.setText("Corretoras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        BtnCadastro.add(jMenuItem1);

        MenuItemProvento.setText("Proventos");
        MenuItemProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventoActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemProvento);

        jMenuBar1.add(BtnCadastro);

        BtnControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/configuracoes.png"))); // NOI18N
        BtnControle.setText("Controle");

        MenuItemEstorno.setText("Estorno");
        MenuItemEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstornoActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemEstorno);

        MenuItemProcessarEvento.setText("Processar Evento");
        MenuItemProcessarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProcessarEventoActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemProcessarEvento);

        jMenuBar1.add(BtnControle);

        MenuItemLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/calendario.png"))); // NOI18N
        MenuItemLogs.setText("Relatórios");

        LogOperacoesCarteira.setText("Histórico de Operações");
        LogOperacoesCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOperacoesCarteiraActionPerformed(evt);
            }
        });
        MenuItemLogs.add(LogOperacoesCarteira);

        MenuItemEventosProcessados.setText("Eventos Processados");
        MenuItemEventosProcessados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEventosProcessadosActionPerformed(evt);
            }
        });
        MenuItemLogs.add(MenuItemEventosProcessados);

        jMenuBar1.add(MenuItemLogs);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotaoProcessamentoDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoProcessamentoDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abrir jalenas já maximizadas:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        carregarTabelaEventos();
    }//GEN-LAST:event_formWindowActivated


    private void btnCadastrarAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtivosActionPerformed

        // Fechar a tela atual e abrir a tela VisaoAdmCadastroAtivo:
        VisaoAdmCadastroAtivo tela = new VisaoAdmCadastroAtivo();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarAtivosActionPerformed


    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked

        // Fechar a Janela atual
        this.dispose();

        // Abre a tela de login novamente
        new TelaDeLogin().setVisible(true);

    }//GEN-LAST:event_btnSairMouseClicked

    private void btnCadastrarAtivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarAtivosMouseClicked
        // Cadastrar:

    }//GEN-LAST:event_btnCadastrarAtivosMouseClicked


    private void btnCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuariosActionPerformed

        // Ação do botão Cadastrar Usuários: 
        new VisaoAdmCadastroUsers().setVisible(true);
        this.dispose(); // Fecha a janela atual

    }//GEN-LAST:event_btnCadastrarUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
 // Ação do botão Cadastrar Usuários: 
        new VisaoAdmCadastroDeCorretoras().setVisible(true);
        this.dispose(); // Fecha a janela atual


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuItemProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventoActionPerformed
        

        // Ação do botão Cadastrar Proventos: 
        new VisaoAdmProventos().setVisible(true);
        this.dispose(); // Fecha a janela atual


    }//GEN-LAST:event_MenuItemProventoActionPerformed

    private void LogOperacoesCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOperacoesCarteiraActionPerformed
        new VisaoAdmLogsDeOperacoes().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_LogOperacoesCarteiraActionPerformed

    private void MenuItemEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstornoActionPerformed
         new VisaoAdmEstorno().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEstornoActionPerformed

    private void BotaoProcessamentoDoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProcessamentoDoEventoActionPerformed
       processarEventoSelecionado();
    }//GEN-LAST:event_BotaoProcessamentoDoEventoActionPerformed

    private void MenuItemProcessarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProcessarEventoActionPerformed
         new VisaoAdministradorProcessarEvento().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemProcessarEventoActionPerformed

    private void MenuItemEventosProcessadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEventosProcessadosActionPerformed
        new VisaoAdministradorEventoProcessado().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEventosProcessadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisaoAdministradorProcessarEvento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoProcessamentoDoEvento;
    private javax.swing.JMenu BtnCadastro;
    private javax.swing.JMenu BtnControle;
    private javax.swing.JMenuItem LogOperacoesCarteira;
    private javax.swing.JLabel Logado;
    private javax.swing.JMenuItem MenuItemEstorno;
    private javax.swing.JMenuItem MenuItemEventosProcessados;
    private javax.swing.JMenu MenuItemLogs;
    private javax.swing.JMenuItem MenuItemProcessarEvento;
    private javax.swing.JMenuItem MenuItemProvento;
    private javax.swing.JTable TabelaProcessamentoDoEvento;
    private javax.swing.JMenuItem btnCadastrarAtivos;
    private javax.swing.JMenuItem btnCadastrarUsuarios;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables

}
