/* ---------------------------------------------------------------------------- */
// 
// 
/* ---------------------------------------------------------------------------- */
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// ============================================================================================
package org.matheus.sibov.view.admin;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.matheus.sibov.dao.AtivoDAO;
import org.matheus.sibov.model.Acao;
import org.matheus.sibov.model.Ativo;
import org.matheus.sibov.model.FII;
import org.matheus.sibov.model.TipoAtivo;

import javax.swing.table.DefaultTableModel;
import java.util.List;
// ============================================================================================

/**
 *
 * @author matheus
 */
public class VisaoAdmCadastroAtivo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoAdmCadastroAtivo.class.getName());

    /**
     * Creates new form VisaoAdministrador
     */
    public VisaoAdmCadastroAtivo() {
        initComponents();

// ============================================================================================
        // Quando mudar de aba, atualiza a tabela // 
        PainelDeAbas.addChangeListener(e -> {
            if (PainelDeAbas.getSelectedIndex() == 1) { // Aba 1 = Listar Ativos
                carregarTabelaAtivos();
            }
// ============================================================================================
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PainelDeAbas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RadioButtonAcao = new javax.swing.JRadioButton();
        RadioButtonFii = new javax.swing.JRadioButton();
        txtTicket = new javax.swing.JTextField();
        txtSegmento = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorCota = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListagemAtivos = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnInserir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnCadastrarAtivos = new javax.swing.JMenuItem();
        MenuItemAtivo = new javax.swing.JMenuItem();
        MenuItemCorretora = new javax.swing.JMenuItem();
        MenuItemProvento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemLogs = new javax.swing.JMenuItem();
        MenuItemEstorno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel administrativo do sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE ATIVOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Ticket: ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Segmento:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Observações: ");

        buttonGroup1.add(RadioButtonAcao);
        RadioButtonAcao.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        RadioButtonAcao.setText("Ação");

        buttonGroup1.add(RadioButtonFii);
        RadioButtonFii.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        RadioButtonFii.setText("FII");

        txtTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketActionPerformed(evt);
            }
        });

        txtObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacoesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Valor da Cota:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(RadioButtonAcao)
                        .addGap(71, 71, 71)
                        .addComponent(RadioButtonFii))
                    .addComponent(txtTicket)
                    .addComponent(txtSegmento)
                    .addComponent(txtObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addComponent(txtValorCota))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RadioButtonAcao)
                    .addComponent(RadioButtonFii))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorCota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PainelDeAbas.addTab("Inserir Ativo", jPanel3);

        TabelaListagemAtivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket", "Tipo", "Segmento", "Observações"
            }
        ));
        TabelaListagemAtivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaListagemAtivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaListagemAtivos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelDeAbas.addTab("Listar Ativos", jPanel4);

        BtnEditar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnInserir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        BtnInserir.setText("Inserir");
        BtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/novo.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        BtnCadastrarAtivos.setText("Ativo");
        BtnCadastrarAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarAtivosActionPerformed(evt);
            }
        });
        jMenu1.add(BtnCadastrarAtivos);

        MenuItemAtivo.setText("Usuário");
        MenuItemAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAtivoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemAtivo);

        MenuItemCorretora.setText("Corretota");
        MenuItemCorretora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCorretoraActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCorretora);

        MenuItemProvento.setText("Provento");
        MenuItemProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemProvento);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/configuracoes.png"))); // NOI18N
        jMenu2.setText("Controle");

        MenuItemLogs.setText("Logs de Movimentações");
        MenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemLogs);

        MenuItemEstorno.setText("Estorno");
        MenuItemEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstornoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemEstorno);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/calendario.png"))); // NOI18N
        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/sair.png"))); // NOI18N
        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeAbas)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnInserir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditar)
                    .addComponent(BtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnInserir});

        getAccessibleContext().setAccessibleName("Cadastro de Ativos | SIBOV ");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // ============================================================================================
        // Abrir jalenas já maximizadas:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
        // ============================================================================================
    }//GEN-LAST:event_formWindowActivated


    private void BtnCadastrarAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarAtivosActionPerformed
        // Fechar a tela atual e abrir a tela VisaoAdmCadastroAtivo:
        VisaoAdmCadastroAtivo tela = new VisaoAdmCadastroAtivo();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCadastrarAtivosActionPerformed

    private void txtTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketActionPerformed

    private void txtObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacoesActionPerformed


    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // Códido executado quando o usuário clicar no botão excluir: 

        try {
            // 1️⃣ Capturar o ticker do campo
            String ticker = txtTicket.getText().trim();

            // 2️⃣ Validar
            if (ticker.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Informe ou selecione um ativo para excluir.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3️⃣ Confirmar exclusão
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja excluir o ativo: " + ticker + "?",
                    "Confirmar Exclusão",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // 4️⃣ Chamar o DAO
            AtivoDAO dao = new AtivoDAO();
            dao.deletarPorTicker(ticker);

            // 5️⃣ Limpar campos
            txtTicket.setText("");
            txtSegmento.setText("");
            txtObservacoes.setText("");
            txtValorCota.setText("");
            RadioButtonAcao.setSelected(false);
            RadioButtonFii.setSelected(false);

            // 6️⃣ Mensagem
            JOptionPane.showMessageDialog(this,
                    "🗑️ Ativo excluído com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir ativo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed


    private void TabelaListagemAtivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaListagemAtivosMouseClicked

// Quando clicar na linha da tabela, chama a aba numero 0: 
        PainelDeAbas.setSelectedIndex(0);

        txtTicket.setText(TabelaListagemAtivos.getValueAt(TabelaListagemAtivos.getSelectedRow(), 0).toString());

        // Preenche os RadioButtons
        String atv = TabelaListagemAtivos.getValueAt(TabelaListagemAtivos.getSelectedRow(), 1).toString();

        if (atv.equals("ACAO")) {
            RadioButtonAcao.setSelected(true);
        } else if (atv.equals("FII")) {
            RadioButtonFii.setSelected(true);
        }

        txtSegmento.setText(TabelaListagemAtivos.getValueAt(TabelaListagemAtivos.getSelectedRow(), 2).toString());

        txtObservacoes.setText(TabelaListagemAtivos.getValueAt(TabelaListagemAtivos.getSelectedRow(), 3).toString());

        txtValorCota.setText(TabelaListagemAtivos.getValueAt(TabelaListagemAtivos.getSelectedRow(), 4).toString());


    }//GEN-LAST:event_TabelaListagemAtivosMouseClicked


    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed

        // Código que roda quando clica em editar: 
        try {
            // 1️⃣ Captura os dados dos campos
            String ticker = txtTicket.getText().trim();
            String segmento = txtSegmento.getText().trim();
            String observacoes = txtObservacoes.getText().trim();
            String valorCotaStr = txtValorCota.getText().trim();

            // Valida se o ticker está preenchido
            if (ticker.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "O campo Ticker é obrigatório para editar.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2️⃣ Verifica qual RadioButton foi selecionado
            TipoAtivo tipo = null;

            if (RadioButtonAcao.isSelected()) {
                tipo = TipoAtivo.ACAO;
            } else if (RadioButtonFii.isSelected()) {
                tipo = TipoAtivo.FII;
            } else {
                JOptionPane.showMessageDialog(this,
                        "Selecione o tipo de ativo (Ação ou FII).",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3️⃣ Converte e valida o valor da cota
            BigDecimal valorCota = null; // ← DECLARA A VARIÁVEL
            if (!valorCotaStr.isEmpty()) {
                try {
                    valorCota = new BigDecimal(valorCotaStr);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this,
                            "Valor da cota inválido! Use formato correto (ex: 150.50).",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // 4️⃣ Cria o tipo correto
            Ativo ativo;
            if (tipo == TipoAtivo.ACAO) {
                ativo = new Acao();
            } else {
                ativo = new FII();
            }

            // 5️⃣ Preenche o ativo
            ativo.setTicker(ticker);
            ativo.setTipo(tipo);
            ativo.setSegmento(segmento);
            ativo.setObservacoes(observacoes);
            ativo.setValorCota(valorCota); // ← AGORA A VARIÁVEL EXISTE

            // 6️⃣ Chama o DAO para atualizar no banco
            AtivoDAO dao = new AtivoDAO();
            dao.atualizar(ativo);

            // 7️⃣ Confirma e limpa
            JOptionPane.showMessageDialog(this,
                    "✅ Ativo alterado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            txtTicket.setText("");
            txtSegmento.setText("");
            txtObservacoes.setText("");
            txtValorCota.setText("");
            RadioButtonAcao.setSelected(false);
            RadioButtonFii.setSelected(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao editar ativo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_BtnEditarActionPerformed


    private void BtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirActionPerformed

        try {
            // 1️⃣ Captura os dados dos campos
            String ticker = txtTicket.getText().trim();
            String segmento = txtSegmento.getText().trim();
            String observacoes = txtObservacoes.getText().trim();
            String valorCotaStr = txtValorCota.getText().trim(); // ← CAPTURA O VALOR DO CAMPO

            // 2️⃣ Verifica qual RadioButton foi selecionado
            TipoAtivo tipo = null;

            if (RadioButtonAcao.isSelected()) {
                tipo = TipoAtivo.ACAO;
            } else if (RadioButtonFii.isSelected()) {
                tipo = TipoAtivo.FII;
            } else {
                JOptionPane.showMessageDialog(this,
                        "Selecione o tipo de ativo (Ação ou FII).",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3️⃣ Converte e valida o valor da cota
            BigDecimal valorCota = null; // ← DECLARA A VARIÁVEL
            if (!valorCotaStr.isEmpty()) {
                try {
                    valorCota = new BigDecimal(valorCotaStr);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this,
                            "Valor da cota inválido! Use formato correto (ex: 150.50).",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // 4️⃣ Cria o objeto correto (Acao ou FII)
            Ativo ativo;
            if (tipo == TipoAtivo.ACAO) {
                ativo = new Acao();
            } else {
                ativo = new FII();
            }

            // 5️⃣ Define os valores no objeto
            ativo.setTicker(ticker);
            ativo.setTipo(tipo);
            ativo.setSegmento(segmento);
            ativo.setObservacoes(observacoes);
            ativo.setValorCota(valorCota); // ← AGORA A VARIÁVEL EXISTE

            // 6️⃣ Chama o DAO para salvar no banco
            AtivoDAO dao = new AtivoDAO();
            dao.salvar(ativo);

            // 7️⃣ Exibe mensagem e limpa os campos
            JOptionPane.showMessageDialog(this,
                    "✅ Ativo cadastrado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            txtTicket.setText("");
            txtSegmento.setText("");
            txtObservacoes.setText("");
            txtValorCota.setText(""); // ← LIMPAR CAMPO
            RadioButtonAcao.setSelected(false);
            RadioButtonFii.setSelected(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao salvar ativo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }


    }//GEN-LAST:event_BtnInserirActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // Fechar a Janela Atual

        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void MenuItemAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAtivoActionPerformed

        new VisaoAdmCadastroUsers().setVisible(true);
        this.dispose(); // Fecha a janela atual
    }//GEN-LAST:event_MenuItemAtivoActionPerformed

    private void MenuItemCorretoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCorretoraActionPerformed

        new VisaoAdmCadastroDeCorretoras().setVisible(true);
        this.dispose(); // Fecha a janela atual


    }//GEN-LAST:event_MenuItemCorretoraActionPerformed

    private void MenuItemProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventoActionPerformed

        new VisaoAdmProventos().setVisible(true);
        this.dispose(); // Fecha a janela atual

    }//GEN-LAST:event_MenuItemProventoActionPerformed

    
    private void MenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogsActionPerformed
        new VisaoAdmLogsDeOperacoes().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemLogsActionPerformed

    
    private void MenuItemEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstornoActionPerformed
         new VisaoAdmEstorno().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEstornoActionPerformed

    
    /**
     * @param args the command line arguments
     */
// MÉTODO PARA CARREGAR LISTAGEM DOS ATIVOS
// ============================================================================================
    private void carregarTabelaAtivos() {
        try {
            AtivoDAO dao = new AtivoDAO();
            List<Ativo> lista = dao.listarTodos();

            DefaultTableModel modelo
                    = (DefaultTableModel) TabelaListagemAtivos.getModel();

            modelo.setRowCount(0);

            for (Ativo a : lista) {
                modelo.addRow(new Object[]{
                    // a.getId(),
                    a.getTicker(),
                    a.getTipo().name(),
                    a.getSegmento(),
                    a.getObservacoes()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar ativos: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // ============================================================================================

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisaoAdmCadastroAtivo().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnCadastrarAtivos;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnInserir;
    private javax.swing.JMenuItem MenuItemAtivo;
    private javax.swing.JMenuItem MenuItemCorretora;
    private javax.swing.JMenuItem MenuItemEstorno;
    private javax.swing.JMenuItem MenuItemLogs;
    private javax.swing.JMenuItem MenuItemProvento;
    private javax.swing.JTabbedPane PainelDeAbas;
    private javax.swing.JRadioButton RadioButtonAcao;
    private javax.swing.JRadioButton RadioButtonFii;
    private javax.swing.JTable TabelaListagemAtivos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtSegmento;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtValorCota;
    // End of variables declaration//GEN-END:variables
}
