/* ---------------------------------------------------------------------------- */
// Visão de cadastro de corretoras e suas respectivas taxas
// 
/* ---------------------------------------------------------------------------- */
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matheus.sibov.view.admin;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.matheus.perfis.Usuario;
import org.matheus.sibov.dao.CorretoraDAO;
import org.matheus.sibov.model.Corretora;
import org.matheus.sibov.view.TelaDeLogin;
import org.matheus.sibov.service.CorretoraService;

/**
 *
 * @author mathe
 */
public class VisaoAdmCadastroDeCorretoras extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoAdmCadastroDeCorretoras.class.getName());

    /**
     * Creates new form VisaoAdministrador
     */
    private Usuario usuarioLogado;

    public VisaoAdmCadastroDeCorretoras() {
        initComponents();
        
        // Listener para carregar corretoras quando a aba "Listar Corretoras" for selecionada
    PainelDeCorretoras.addChangeListener(e -> {
        if (PainelDeCorretoras.getSelectedIndex() == 1) { // índice da aba "Listar Corretoras"
            carregarCorretorasNaTabela();
        }
    });
        
    }

    public VisaoAdmCadastroDeCorretoras(Usuario user) {
        this.usuarioLogado = user;
        initComponents();
        carregarDadosUsuario();
    }

    private void carregarDadosUsuario() {
        if (usuarioLogado != null) {
            txtUsuarioLogado.setText(usuarioLogado.getNome());
        }
    }

    // -----------------------------------------------------------------------------
// Métodos auxiliares da tela de cadastro de corretoras
// - parseDecimal(String valor): converte o texto digitado em BigDecimal,
//   tratando valores nulos, strings vazias e substituindo vírgula por ponto.
//   Caso o valor seja inválido, retorna ZERO e exibe uma mensagem de validação.

    private BigDecimal parseDecimal(String valor) {
        if (valor == null) {
            return BigDecimal.ZERO;
        }
        String v = valor.trim().replace(",", ".");
        if (v.isEmpty()) {
            return BigDecimal.ZERO;
        }
        try {
            return new BigDecimal(v);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Valor inválido: " + valor, "Validação", JOptionPane.WARNING_MESSAGE);
            return BigDecimal.ZERO;
        }
    }

    // - limparCampos(): reseta os campos de entrada da tela (nome, taxas e observações),
//   deixando-os prontos para um novo cadastro.
    
    private void limparCampos() {
        txtCorretora.setText("");
        txtTaxaFixa.setText("");
        txtTaxaPercentual.setText("");
        txtObservacoes.setText("");
    }
    
    
    
    private void carregarCorretorasNaTabela() {
    try {
        CorretoraDAO dao = new CorretoraDAO();
        java.util.List<Corretora> lista = dao.listarTodas();

        // Modelo da tabela
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Corretora", "Taxa Fixa", "Taxa Percentual", "Observações"}, 0
        );

        // Preenche a tabela
        for (Corretora c : lista) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getTaxaFixa(),
                c.getTaxaPercentual(),
                c.getObservacoes()
            });
        }

        TabelaListagemDeCorretoras.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar corretoras: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logado = new javax.swing.JLabel();
        txtUsuarioLogado = new javax.swing.JLabel();
        PainelDeCorretoras = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nome_da_Corretora = new javax.swing.JLabel();
        Taxa_Fixa = new javax.swing.JLabel();
        Taxa_percentual = new javax.swing.JLabel();
        Observacoes = new javax.swing.JLabel();
        txtObservacoes = new javax.swing.JTextField();
        txtTaxaPercentual = new javax.swing.JTextField();
        txtTaxaFixa = new javax.swing.JTextField();
        txtCorretora = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListagemDeCorretoras = new javax.swing.JTable();
        BntInserir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnCadastro = new javax.swing.JMenu();
        MenuItemAtivo = new javax.swing.JMenuItem();
        MenuItemUsuario = new javax.swing.JMenuItem();
        MenuItemCorretora = new javax.swing.JMenuItem();
        MenuItemProvento = new javax.swing.JMenuItem();
        BtnControle = new javax.swing.JMenu();
        MenuItemLogs = new javax.swing.JMenuItem();
        MenuItemEstornos = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel administrativo do sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CORRETORAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        Logado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Logado.setText("Usuário logado:");

        txtUsuarioLogado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuarioLogado.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuarioLogado.setText("Matheus Ribeiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioLogado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logado)
                    .addComponent(txtUsuarioLogado))
                .addGap(34, 34, 34))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CADASTRAR CORRETORA");

        Nome_da_Corretora.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Nome_da_Corretora.setText("Nome da corretora:");

        Taxa_Fixa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Taxa_Fixa.setText("Taxa Fixa( Opcional ):");

        Taxa_percentual.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Taxa_percentual.setText("Taxa Percentual ( Opcional ):");

        Observacoes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Observacoes.setText("Observações:");

        txtObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacoesActionPerformed(evt);
            }
        });

        txtTaxaPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxaPercentualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Taxa_Fixa)
                            .addComponent(Nome_da_Corretora, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Taxa_percentual)
                            .addComponent(Observacoes))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtObservacoes))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTaxaPercentual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                                    .addComponent(txtCorretora)
                                    .addComponent(txtTaxaFixa))))))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome_da_Corretora)
                    .addComponent(txtCorretora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Taxa_Fixa)
                    .addComponent(txtTaxaFixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaxaPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Taxa_percentual))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Observacoes))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        PainelDeCorretoras.addTab("Cadastrar Corretora", jPanel3);

        TabelaListagemDeCorretoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Corretora", "Taxa Fixa", "Taxa Percental", "Observações"
            }
        ));
        jScrollPane1.setViewportView(TabelaListagemDeCorretoras);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeCorretoras.addTab("Listar Corretoras", jPanel4);

        BntInserir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BntInserir.setText("Inserir");
        BntInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntInserirActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        BtnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/novo.png"))); // NOI18N
        BtnCadastro.setText("Cadastros");

        MenuItemAtivo.setText("Ativo");
        MenuItemAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemAtivoMouseClicked(evt);
            }
        });
        MenuItemAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAtivoActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemAtivo);

        MenuItemUsuario.setText("Usuário");
        MenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuarioActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemUsuario);

        MenuItemCorretora.setText("Corretora");
        MenuItemCorretora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCorretoraActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemCorretora);

        MenuItemProvento.setText("Provento");
        MenuItemProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventoActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemProvento);

        jMenuBar1.add(BtnCadastro);

        BtnControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/configuracoes.png"))); // NOI18N
        BtnControle.setText("Controle");

        MenuItemLogs.setText("Logs de Movimentações");
        MenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogsActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemLogs);

        MenuItemEstornos.setText("Estorno");
        MenuItemEstornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstornosActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemEstornos);

        jMenuBar1.add(BtnControle);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/calendario.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        jMenuBar1.add(btnRelatorios);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeCorretoras)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BntInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelDeCorretoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BntInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abrir jalenas já maximizadas:
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowActivated


    private void MenuItemAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAtivoActionPerformed

        VisaoAdmCadastroAtivo tela = new VisaoAdmCadastroAtivo();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAtivoActionPerformed


    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked

        // Fechar a Janela atual
        this.dispose();

        // Abre a tela de login novamente
        new TelaDeLogin().setVisible(true);

    }//GEN-LAST:event_btnSairMouseClicked

    private void MenuItemAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemAtivoMouseClicked
        // Cadastrar:

    }//GEN-LAST:event_MenuItemAtivoMouseClicked


    private void MenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuarioActionPerformed

        // Ação do botão Cadastrar Usuários: 
        new VisaoAdmCadastroUsers().setVisible(true);
        this.dispose(); // Fecha a janela atual

    }//GEN-LAST:event_MenuItemUsuarioActionPerformed

    private void txtObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacoesActionPerformed

    private void txtTaxaPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxaPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxaPercentualActionPerformed

    private void BntInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntInserirActionPerformed

// 
        try {
            Corretora c = new Corretora();
            c.setNome(txtCorretora.getText());
            c.setTaxaFixa(parseDecimal(txtTaxaFixa.getText()));
            c.setTaxaPercentual(parseDecimal(txtTaxaPercentual.getText()));
            c.setObservacoes(txtObservacoes.getText());

            // Validação via Service
            CorretoraService service = new CorretoraService();
            service.validar(c);

            // Persistência via DAO
            CorretoraDAO dao = new CorretoraDAO();
            dao.inserir(c);

            JOptionPane.showMessageDialog(this, "Corretora cadastrada com sucesso!");
            limparCampos();

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validação", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar corretora: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BntInserirActionPerformed

    private void MenuItemCorretoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCorretoraActionPerformed
         new VisaoAdmCadastroDeCorretoras().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemCorretoraActionPerformed

    private void MenuItemProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventoActionPerformed
         new VisaoAdmProventos().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemProventoActionPerformed

    private void MenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogsActionPerformed
         new VisaoAdmLogsDeOperacoes().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemLogsActionPerformed

    private void MenuItemEstornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstornosActionPerformed
        new VisaoAdmEstorno().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEstornosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisaoAdmCadastroDeCorretoras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntInserir;
    private javax.swing.JMenu BtnCadastro;
    private javax.swing.JMenu BtnControle;
    private javax.swing.JLabel Logado;
    private javax.swing.JMenuItem MenuItemAtivo;
    private javax.swing.JMenuItem MenuItemCorretora;
    private javax.swing.JMenuItem MenuItemEstornos;
    private javax.swing.JMenuItem MenuItemLogs;
    private javax.swing.JMenuItem MenuItemProvento;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JLabel Nome_da_Corretora;
    private javax.swing.JLabel Observacoes;
    private javax.swing.JTabbedPane PainelDeCorretoras;
    private javax.swing.JTable TabelaListagemDeCorretoras;
    private javax.swing.JLabel Taxa_Fixa;
    private javax.swing.JLabel Taxa_percentual;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCorretora;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtTaxaFixa;
    private javax.swing.JTextField txtTaxaPercentual;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables

}
