/* ---------------------------------------------------------------------------- */
// 
// 
/* ---------------------------------------------------------------------------- */
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matheus.sibov.view.admin;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.matheus.perfis.Usuario;
import org.matheus.sibov.dao.AtivoDAO;
import org.matheus.sibov.dao.ProventoDAO;
import org.matheus.sibov.model.Ativo;
import org.matheus.sibov.model.Provento;
import org.matheus.sibov.model.StatusProvento;
import org.matheus.sibov.model.TipoProvento;
import org.matheus.sibov.view.TelaDeLogin;

import org.matheus.sibov.view.admin.VisaoAdmCadastroUsers;

/**
 *
 * @author mathe
 */
public class VisaoAdmProventos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoAdmProventos.class.getName());
    
   

    /**
     * Creates new form VisaoAdministrador
     */
    private Usuario usuarioLogado;

    public VisaoAdmProventos() {
        initComponents();
        carregarTabelaAtivos();
        carregarTabelaAtivosComProventos();
    }

    public VisaoAdmProventos(Usuario user) {
        this.usuarioLogado = user;
        initComponents();
        carregarDadosUsuario();
    }

    private void carregarDadosUsuario() {
        if (usuarioLogado != null) {
            txtUsuarioLogado.setText(usuarioLogado.getNome());
        }
    }
    
    
    
/* ---------------------------------------------------------------------------- */
// Método para preencher a tabela de ativos
/* ---------------------------------------------------------------------------- */
    
    private void carregarTabelaAtivos() {
    AtivoDAO dao = new AtivoDAO();
    List<Ativo> lista = dao.listarTodos();

    DefaultTableModel modelo = (DefaultTableModel) TabelaListarAtivosDisponiveis.getModel();
    modelo.setRowCount(0); // limpa a tabela

    for (Ativo ativo : lista) {
        modelo.addRow(new Object[]{
            ativo.getId(),
            ativo.getTicker(),
            ativo.getTipo().name()
        });
    }
}
    
    /* ---------------------------------------------------------------------------- */
// Método para Limpar os campos após salvar
/* ---------------------------------------------------------------------------- */
    private void limparCamposProvento() {
    txtIdAtivo.setText("");
    txtTipoProvento.setText("");
    txtValorCota.setText("");
    txtDataCom.setText("");
    txtDataEx.setText("");
    txtDataPagamento.setText("");
    txtStatus.setText("");
    txtObservacoes.setText("");
}
    
    
    
    
    private void carregarTabelaAtivosComProventos() {
   
        
        ProventoDAO dao = new ProventoDAO();
    List<Object[]> lista = dao.listarAtivosComProventos();

    DefaultTableModel modelo = (DefaultTableModel) TabelaAtivosComProventos.getModel();
    modelo.setRowCount(0); // limpa

    for (Object[] linha : lista) {
        modelo.addRow(linha);
    }
        
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logado = new javax.swing.JLabel();
        txtUsuarioLogado = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListarAtivosDisponiveis = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaAtivosComProventos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdAtivo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTipoProvento = new javax.swing.JTextField();
        txtValorCota = new javax.swing.JTextField();
        txtDataCom = new javax.swing.JTextField();
        txtDataEx = new javax.swing.JTextField();
        txtDataPagamento = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtObservacoes = new javax.swing.JTextField();
        BtnCadastrarProventoSelecionado = new javax.swing.JButton();
        BtnSalvarProvento = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnCadastro = new javax.swing.JMenu();
        MenuItemAtivo = new javax.swing.JMenuItem();
        MenuItemUsuario = new javax.swing.JMenuItem();
        MenuItemCorretora = new javax.swing.JMenuItem();
        MenuItemProvento = new javax.swing.JMenuItem();
        BtnControle = new javax.swing.JMenu();
        MenuItemLogs = new javax.swing.JMenuItem();
        MenuItemEstornos = new javax.swing.JMenuItem();
        btnRelatorios = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel administrativo do sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROVENTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        Logado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Logado.setText("Usuário logado:");

        txtUsuarioLogado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuarioLogado.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuarioLogado.setText("Matheus Ribeiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioLogado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logado)
                    .addComponent(txtUsuarioLogado))
                .addGap(34, 34, 34))
        );

        TabelaListarAtivosDisponiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ticket", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(TabelaListarAtivosDisponiveis);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Ativos disponíveis", jPanel5);

        TabelaAtivosComProventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ticket", "Valor da Cota", "Tipo de Provento", "Valor por cota", "Data de Pagamento", "Status"
            }
        ));
        jScrollPane2.setViewportView(TabelaAtivosComProventos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Ativos com proventos", jPanel4);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Id do ativo:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Tipo do provento: ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Valor por cota:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("DATA_COM");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("DATA_EX");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Data do pagamento: ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Status:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Observações:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataCom, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoProvento, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorCota, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(txtDataEx))
                                .addComponent(jLabel6)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                    .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10))))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoProvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorCota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDataEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Inserir - Editar Provento", jPanel3);

        BtnCadastrarProventoSelecionado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCadastrarProventoSelecionado.setText("Selecionar Provento");
        BtnCadastrarProventoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarProventoSelecionadoActionPerformed(evt);
            }
        });

        BtnSalvarProvento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSalvarProvento.setText("Salvar");
        BtnSalvarProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarProventoActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        BtnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/novo.png"))); // NOI18N
        BtnCadastro.setText("Cadastros");

        MenuItemAtivo.setText("Ativo");
        MenuItemAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemAtivoMouseClicked(evt);
            }
        });
        MenuItemAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAtivoActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemAtivo);

        MenuItemUsuario.setText("Usuário");
        MenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuarioActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemUsuario);

        MenuItemCorretora.setText("Corretora");
        MenuItemCorretora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCorretoraActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemCorretora);

        MenuItemProvento.setText("Provento");
        MenuItemProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventoActionPerformed(evt);
            }
        });
        BtnCadastro.add(MenuItemProvento);

        jMenuBar1.add(BtnCadastro);

        BtnControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/configuracoes.png"))); // NOI18N
        BtnControle.setText("Controle");

        MenuItemLogs.setText("Logs de Operações");
        MenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogsActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemLogs);

        MenuItemEstornos.setText("Estornos");
        MenuItemEstornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstornosActionPerformed(evt);
            }
        });
        BtnControle.add(MenuItemEstornos);

        jMenuBar1.add(BtnControle);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/calendario.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        jMenuBar1.add(btnRelatorios);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BtnCadastrarProventoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSalvarProvento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnCadastrarProventoSelecionado, BtnSalvarProvento});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrarProventoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalvarProvento))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnCadastrarProventoSelecionado, BtnSalvarProvento});

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abrir jalenas já maximizadas:
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowActivated


    private void MenuItemAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAtivoActionPerformed

        // Fechar a tela atual e abrir a tela VisaoAdmCadastroAtivo:
        VisaoAdmCadastroAtivo tela = new VisaoAdmCadastroAtivo();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemAtivoActionPerformed


    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked

        // Fechar a Janela atual
        this.dispose();

        // Abre a tela de login novamente
        new TelaDeLogin().setVisible(true);

    }//GEN-LAST:event_btnSairMouseClicked

    private void MenuItemAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemAtivoMouseClicked
        // Cadastrar:

    }//GEN-LAST:event_MenuItemAtivoMouseClicked


    private void MenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuarioActionPerformed
 
        new VisaoAdmCadastroUsers().setVisible(true);
        this.dispose(); // Fecha a janela atual
    }//GEN-LAST:event_MenuItemUsuarioActionPerformed

    private void MenuItemCorretoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCorretoraActionPerformed

        new VisaoAdmCadastroDeCorretoras().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemCorretoraActionPerformed

    private void BtnCadastrarProventoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarProventoSelecionadoActionPerformed
        
        int linha = TabelaListarAtivosDisponiveis.getSelectedRow();

    if (linha != -1) {
        int idAtivo = (int) TabelaListarAtivosDisponiveis.getValueAt(linha, 0);
        txtIdAtivo.setText(String.valueOf(idAtivo));

        // Buscar ativo no banco para já preencher o tipo de rendimento
        AtivoDAO dao = new AtivoDAO();
        Ativo ativo = dao.buscarPorId(idAtivo);

        if (ativo != null) {
            if (ativo.getTipo().name().equals("FII")) {
                txtTipoProvento.setText("RENDIMENTO_FII");
            } else if (ativo.getTipo().name().equals("ACAO")) {
                txtTipoProvento.setText("DIVIDENDO"); // padrão
            }
        }

        jTabbedPane1.setSelectedIndex(2); // vai para aba "Inserir - Editar Provento"
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um ativo na tabela para cadastrar provento.");
    }
        
    }//GEN-LAST:event_BtnCadastrarProventoSelecionadoActionPerformed

    private void BtnSalvarProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarProventoActionPerformed
        
        try {
        Provento provento = new Provento();
        provento.setIdAtivo(Integer.parseInt(txtIdAtivo.getText()));
        provento.setTipo(TipoProvento.valueOf(txtTipoProvento.getText().toUpperCase()));
        provento.setValorPorCota(new BigDecimal(txtValorCota.getText()));
        provento.setDataCom(LocalDate.parse(txtDataCom.getText()));
        provento.setDataEx(LocalDate.parse(txtDataEx.getText()));
        provento.setDataPagamento(LocalDate.parse(txtDataPagamento.getText()));
        provento.setStatus(StatusProvento.valueOf(txtStatus.getText().toUpperCase()));
        provento.setObservacoes(txtObservacoes.getText());

        ProventoDAO dao = new ProventoDAO();
        dao.salvar(provento);

        JOptionPane.showMessageDialog(this, "Provento salvo com sucesso!");
        limparCamposProvento();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar provento: " + e.getMessage());
    }


    }//GEN-LAST:event_BtnSalvarProventoActionPerformed

    private void MenuItemProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventoActionPerformed
         new VisaoAdmProventos().setVisible(true);
        this.dispose(); // Fecha a janela atual
    }//GEN-LAST:event_MenuItemProventoActionPerformed

    private void MenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogsActionPerformed
         new VisaoAdmLogsDeOperacoes().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemLogsActionPerformed

    private void MenuItemEstornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstornosActionPerformed
       new VisaoAdmEstorno().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEstornosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisaoAdmProventos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarProventoSelecionado;
    private javax.swing.JMenu BtnCadastro;
    private javax.swing.JMenu BtnControle;
    private javax.swing.JButton BtnSalvarProvento;
    private javax.swing.JLabel Logado;
    private javax.swing.JMenuItem MenuItemAtivo;
    private javax.swing.JMenuItem MenuItemCorretora;
    private javax.swing.JMenuItem MenuItemEstornos;
    private javax.swing.JMenuItem MenuItemLogs;
    private javax.swing.JMenuItem MenuItemProvento;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JTable TabelaAtivosComProventos;
    private javax.swing.JTable TabelaListarAtivosDisponiveis;
    private javax.swing.JMenu btnRelatorios;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDataCom;
    private javax.swing.JTextField txtDataEx;
    private javax.swing.JTextField txtDataPagamento;
    private javax.swing.JTextField txtIdAtivo;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTipoProvento;
    private javax.swing.JLabel txtUsuarioLogado;
    private javax.swing.JTextField txtValorCota;
    // End of variables declaration//GEN-END:variables

}
