/* ---------------------------------------------------------------------------- */
// 
// 
/* ---------------------------------------------------------------------------- */
 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matheus.sibov.view.admin;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.matheus.perfis.Administrador;
import org.matheus.perfis.Investidor;
import org.matheus.perfis.Usuario;
import org.matheus.sibov.service.UsuarioService;

/**
 *
 * @author mathe
 */
public class VisaoAdmCadastroUsers extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisaoAdmCadastroUsers.class.getName());
    private UsuarioService usuarioService = new UsuarioService(); // <-- CORRETO

    /**
     * Creates new form VisaoAdministrador
     */
    public VisaoAdmCadastroUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void listarUsuarios() {

        UsuarioService service = new UsuarioService();

        // Busca todos os usuários usando o service
        var lista = service.buscarTodos();

        // Atualiza a tabela
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Usuarios.getModel();
        modelo.setRowCount(0);

        for (Usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getNome(),
                u.getEmail(),
                u.getCpf(),
                u.getPerfil()
            });
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        GrupoUsuarios = new javax.swing.ButtonGroup();
        BarraVerdeSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BarraVerdeInferior = new javax.swing.JPanel();
        PainelCrudUsuarios = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RadioButton01 = new javax.swing.JRadioButton();
        RadioButton02 = new javax.swing.JRadioButton();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Usuarios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        MenuSuperior = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemAtivo = new javax.swing.JMenuItem();
        MenuItemUsuario = new javax.swing.JMenuItem();
        MenuItemCorretora = new javax.swing.JMenuItem();
        MenuItemProvento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemLogs = new javax.swing.JMenuItem();
        MenuItemEstorno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel administrativo do sistema financeiro SIBOV");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BarraVerdeSuperior.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE USUÁRIOS");

        javax.swing.GroupLayout BarraVerdeSuperiorLayout = new javax.swing.GroupLayout(BarraVerdeSuperior);
        BarraVerdeSuperior.setLayout(BarraVerdeSuperiorLayout);
        BarraVerdeSuperiorLayout.setHorizontalGroup(
            BarraVerdeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BarraVerdeSuperiorLayout.setVerticalGroup(
            BarraVerdeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraVerdeSuperiorLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        BarraVerdeInferior.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout BarraVerdeInferiorLayout = new javax.swing.GroupLayout(BarraVerdeInferior);
        BarraVerdeInferior.setLayout(BarraVerdeInferiorLayout);
        BarraVerdeInferiorLayout.setHorizontalGroup(
            BarraVerdeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraVerdeInferiorLayout.setVerticalGroup(
            BarraVerdeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Email: ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Senha: ");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Perfil de Usuário: ");

        GrupoUsuarios.add(RadioButton01);
        RadioButton01.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RadioButton01.setText("Administrador");
        RadioButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton01ActionPerformed(evt);
            }
        });

        GrupoUsuarios.add(RadioButton02);
        RadioButton02.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RadioButton02.setText("Investidor");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtEmail)
                    .addComponent(txtCpf)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(RadioButton01)
                        .addGap(71, 71, 71)
                        .addComponent(RadioButton02)
                        .addGap(0, 416, Short.MAX_VALUE))
                    .addComponent(txtSenha))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RadioButton01)
                    .addComponent(RadioButton02))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        PainelCrudUsuarios.addTab("Cadastrar Usuários", jPanel3);

        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "Email:", "CPF:", "Perfil:"
            }
        ));
        Tabela_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Usuarios);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Pesquisa: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelCrudUsuarios.addTab("Listar Usuários", jPanel5);

        BtnEditar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excluir.png"))); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        BtnSalvar.setText("Inserir");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        MenuSuperior.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/novo.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        menuItemAtivo.setText("Ativo");
        menuItemAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAtivoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAtivo);

        MenuItemUsuario.setText("Usuário");
        MenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemUsuario);

        MenuItemCorretora.setText("Corretora");
        MenuItemCorretora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCorretoraActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCorretora);

        MenuItemProvento.setText("Provento");
        MenuItemProvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProventoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemProvento);

        MenuSuperior.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/configuracoes.png"))); // NOI18N
        jMenu2.setText("Controle");

        MenuItemLogs.setText("Logs de Operações");
        MenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemLogs);

        MenuItemEstorno.setText("Estorno");
        MenuItemEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEstornoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemEstorno);

        MenuSuperior.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/calendario.png"))); // NOI18N
        jMenu3.setText("Relatórios");
        MenuSuperior.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/matheus/images/sair.png"))); // NOI18N
        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        MenuSuperior.add(jMenu4);

        setJMenuBar(MenuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraVerdeSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCrudUsuarios)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraVerdeInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraVerdeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelCrudUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(BarraVerdeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnSalvar});

        getAccessibleContext().setAccessibleName("Cadastro de Usuarios  | SIBOV");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abrir jalenas já maximizadas:

        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);

        listarUsuarios(); // Atualiza a tabela sempre que abrir
    }//GEN-LAST:event_formWindowActivated


    private void menuItemAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAtivoActionPerformed
        new VisaoAdmCadastroAtivo().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_menuItemAtivoActionPerformed

    private void MenuItemProventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProventoActionPerformed
         new VisaoAdmProventos().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemProventoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void RadioButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton01ActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed


    private void Tabela_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_UsuariosMouseClicked
        // Pegar os Dados e muda para aba de índice 0:
        PainelCrudUsuarios.setSelectedIndex(0);

        // Pega a linha selecionada 
        int row = Tabela_Usuarios.getSelectedRow();

        txtNome.setText(Tabela_Usuarios.getValueAt(row, 0).toString());
        txtEmail.setText(Tabela_Usuarios.getValueAt(row, 1).toString());
        txtCpf.setText(Tabela_Usuarios.getValueAt(row, 2).toString());

//  Nunca preencher senha — risco grave de segurança
        txtSenha.setText(""); // limpa o campo

// Preenche os RadioButtons
        String perfil = Tabela_Usuarios.getValueAt(row, 3).toString();

        if (perfil.equals("ADMINISTRADOR")) {
            RadioButton01.setSelected(true);
        } else if (perfil.equals("INVESTIDOR")) {
            RadioButton02.setSelected(true);
        }


    }//GEN-LAST:event_Tabela_UsuariosMouseClicked

    /* --------  ---------Eventos do Botão de Ecluir --      -------------- */
    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:

        int row = Tabela_Usuarios.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário para excluir.");
            return;
        }

        String cpf = Tabela_Usuarios.getValueAt(row, 2).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Excluir o usuário com CPF: " + cpf + "?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                usuarioService.deletarPorCpf(cpf);
                JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");

                listarUsuarios(); // ← Atualiza a tabela
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }


    }//GEN-LAST:event_BtnExcluirActionPerformed


    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed

        try {
            /* 1️⃣ Captura os dados dos campos */
            String nome = txtNome.getText();
            String email = txtEmail.getText();
            String cpf = txtCpf.getText();
            String senha = txtSenha.getText();

            /* 2️⃣ Verifica o perfil com base no radio selecionado */
            Usuario usuario;
            if (RadioButton01.isSelected()) {
                usuario = new Administrador();
            } else if (RadioButton02.isSelected()) {
                usuario = new Investidor();
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um perfil!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            /* 3️⃣ Preenche os dados */
            usuario.setNome(nome);
            usuario.setEmail(email);
            usuario.setCpf(cpf);   // usado para localizar o usuário no banco
            usuario.setSenha(senha);
            // Perfil vem da classe concreta (Administrador ou Investidor)
            usuario.setPerfil(usuario.getPerfil());

            /* 4️⃣ Chamada ao SERVICE */
            UsuarioService service = new UsuarioService();

            try {
                service.atualizarUsuario(usuario);  // <-- Chama o service para tratar a edição
                JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            /* 5️⃣ Limpar os campos */
            txtNome.setText("");
            txtEmail.setText("");
            txtCpf.setText("");
            txtSenha.setText("");
            RadioButton01.setSelected(false);
            RadioButton02.setSelected(false);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BtnEditarActionPerformed


    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // Fechar a janela atual

        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    
    
    private void MenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuarioActionPerformed
         new VisaoAdmCadastroUsers().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemUsuarioActionPerformed

    
    
    private void MenuItemCorretoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCorretoraActionPerformed
         new VisaoAdmCadastroDeCorretoras().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemCorretoraActionPerformed

    private void MenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogsActionPerformed
        new VisaoAdmLogsDeOperacoes().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemLogsActionPerformed

    private void MenuItemEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEstornoActionPerformed
         new VisaoAdmEstorno().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MenuItemEstornoActionPerformed

    
    
    
    
    
    /* Botão de INSERIR */
    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            /* Captura os dados dos campos */
            String nome = txtNome.getText();
            String email = txtEmail.getText();
            String cpf = txtCpf.getText();
            String senha = txtSenha.getText();

            /* Determina o perfil com base no radio selecionado */
            Usuario usuario;
            if (RadioButton01.isSelected()) {
                usuario = new Administrador();
            } else if (RadioButton02.isSelected()) {
                usuario = new Investidor();
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um perfil!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            /* Preenche os dados */
            usuario.setNome(nome);
            usuario.setEmail(email);
            usuario.setCpf(cpf);
            usuario.setSenha(senha);

            /* CHAMADA AO SERVICE */
            UsuarioService service = new UsuarioService();

            try {
                service.cadastrarUsuario(usuario);
                JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 5️⃣ Limpar os campos
            txtNome.setText("");
            txtEmail.setText("");
            txtCpf.setText("");
            txtSenha.setText("");
            RadioButton01.setSelected(false);
            RadioButton02.setSelected(false);

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /* ------------------------------------------------------------------------*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Aplica o tema Windows */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


        /* Abre a tela */
        java.awt.EventQueue.invokeLater(() -> {
            new VisaoAdmCadastroUsers().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraVerdeInferior;
    private javax.swing.JPanel BarraVerdeSuperior;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.ButtonGroup GrupoUsuarios;
    private javax.swing.JMenuItem MenuItemCorretora;
    private javax.swing.JMenuItem MenuItemEstorno;
    private javax.swing.JMenuItem MenuItemLogs;
    private javax.swing.JMenuItem MenuItemProvento;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JMenuBar MenuSuperior;
    private javax.swing.JTabbedPane PainelCrudUsuarios;
    private javax.swing.JRadioButton RadioButton01;
    private javax.swing.JRadioButton RadioButton02;
    private javax.swing.JTable Tabela_Usuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItemAtivo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
